ansible/host_vars/master-small-01.aws-eu-central-1a.nimbus.pyrmont.yml
ansible/inventory/test
ansible/roles/beacon-node-builds/README.md
ansible/roles/beacon-node-builds/templates/build.sh.j2

- build with "-d:noSignalHandler" in NIMFLAGS
- keep binary copies for a week, so we can use them with core dumps on target hosts
- finish replacing "item.branch" with "item.version"
- manually add a [nimbus-master] section to "ansible/inventory/test" (FIXME: this should be automatically generated)

beacon-node-builds: support core dumps

---

Makefile
scripts/create-ssh-config.sh

`make ssh-config` will generate a file `~/.ssh/config.d/infra-numbus` with all
hostnames from the Ansible inventory. You can `Include` this file from your
main config file and re-generate it at will at any time. Having such a config
file makes it easier to ssh into any host on the fleet by taking advantage of
the built-in ssh hostname autocompletion in your shell.
The names of the entries were chosen in a way such that typing:
```
ssh nimbus<tab>goerli<tab>
```
... produces the expected result.

Simple Makefile target for generating a SSH config file with the fleet hosts

---

providers.tf
secrets.tf
versions.tf

I was experiencing errors when using the pass provider:
```
Error: rpc error: code = Unavailable desc = transport is closing
```
With lot of errors in the log:
```
2021-03-29T12:56:28.109+0800 [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unimplemented desc = unknown service plugin.GRPCStdio"
2021-03-29T12:56:28.265+0800 [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
```
Upgrading to the latest version of the pass provider fixes the problem for me.
Terraform 0.14.4

upgrade tf pass provider to 2.0.0

---

Makefile
ansible/geth.yml
ansible/logs.yml
ansible/mainnet.yml
ansible/prater.yml
ansible/pyrmont.yml
ansible/requirements.yml
ansible/versioncheck.py

Since Ansible or Ansible Galaxy doesn't actually check role versions itself, we have to do it ourselves. This script goes through contents of `ansible/requirements.txt` and verifies each role is installed and has correct version.
```
> ansible/versioncheck.py
nginx - VALID
origin-certs - VALID
open-ports - VALID
infra-role-tinc - VALID
infra-role-bootstrap - VALID
oauth-proxy - VALID
consul-service - VALID
infra-role-beacon-node - MISMATCH: 0a57ff8b != 96bd1688
kibana - VALID
elasticsearch - VALID
elasticsearch-hq - VALID
elasticsearch-lb - VALID
systemd-timer - VALID
swap-file - MISSING!
infra-role-geth - VALID
infra-role-geth-exporter - VALID
```
It also checks the version of Ansible itself.
@arthurk please verify this works for you locally.
I would probably want to roll this out to all …

add versioncheck.py script to verify Ansible role versions

---

ansible/group_vars/nimbus.prater.yml
ansible/group_vars/nimbus.pyrmont.yml

The default `v2` mode is now sufficiently tested, so we don't need to run more A/B testing experiments.

Use the default slashing DB kind (v2)

---

modules/hetzner/README.md
modules/hetzner/main.tf
modules/hetzner/variables.tf
modules/hetzner/versions.tf

This is a dummy module for our dedicated hetzner server. We do this to keep our ansible inventory consistent with other modules.
I've tested this module by creating a `stable-hetzner-01.he-eu-hel1.nimbus.prater` host and running our ansible bootstrap script on it. Everything worked and we can continue with the server setup. I'm going to reset/delete the test-server and we can discuss next what we want to run on the server.

add terraform hetzner dummy module

---

ansible/roles/get-geth-web3-urls/tasks/main.yml

Instead of assuming there is a geth node running in the same datacenter it will scan all data center's for nodes that match the network.
This is necessary for #56 since we don't have a mainnet node running in the hetzner DC and it would take too long to set one up. With this change it will discover the mainnet node in the AWS dc and use it.

Scan all DC's for Geth nodes

---

ansible/group_vars/nimbus-mainnet-metal.yml
ansible/host_vars/stable-metal-01.he-eu-hel1.nimbus.mainnet.yml
ansible/inventory/test
ansible/mainnet.yml
mainnet.tf
modules/hetzner/main.tf

This PR adds the hetzner dedicated server mentioned in #52 to the infra.
The server will run stable branch on mainnet.
The builds are set up and work:
https://hub.docker.com/layers/statusteam/nimbus_beacon_node/stable-metal-01/images/sha256-3f38ccf62e519cf4beaeda5c82bcd6bb9887aea325221b6c8da6580632d0ade9?context=explore
However, the problem is that the server is not added to the ansible inventory under `[nimbus.mainnet]`,
which prevents the `infra-role-beacon-node` role to run. I'm looking more into
it.

Add hetzner dedicated server

---

ansible/group_vars/nimbus-geth-goerli.yml
ansible/group_vars/nimbus.rayonism.yml
ansible/prater.yml
ansible/pyrmont.yml
ansible/requirements.yml
ansible/rocketpool.yml

I've used this to deploy the latest version of the RocketPool smart node to the now obsolete Rayonism host.
The RocketPool setup consist of 3 services:
1) A nimbus beacon node connect to the Prater network and the Goerli Geth instance. The web3 URLs for this must be specified in the variables `rocketpool_web3_url` and `rocketpool_web3_ws_url` of the rocketpool-smart-node role.
2) rocketpool-node - A regular instance of the rocketpool daemon
3) rocketpool-watchtower - A special node performing oracle services within the RocketPool network. Once the deployment is complete, we'll have to carry out some manual operations on the host to install our private oracle credentials.
The services have been configured by following the practices of the following guide: …

Experimental deployment of RocketPool on the Rayonism host

---

ansible/group_vars/nimbus.mainnet.yml
ansible/group_vars/nimbus.prater.yml
ansible/group_vars/nimbus.pyrmont.yml
ansible/requirements.yml

The idea here is to conditionally enable support for the new light client server arguments depending on whether the node is using a repo branch that supports the corresponding launch arguments.
- Linux: https://github.com/status-im/infra-role-beacon-node-linux/pull/7
- macOS: https://github.com/status-im/infra-role-beacon-node-macos/pull/3
- Windows: https://github.com/status-im/infra-role-beacon-node-windows/pull/2

nimbus: mark branches supporting BN light client server

---

ansible/group_vars/nimbus.kiln.yml
ansible/group_vars/nimbus.mainnet.yml
ansible/group_vars/nimbus.prater.yml
ansible/group_vars/nimbus.ropsten.yml

On `kiln`, `ropsten`, `prater`, `sepolia`, the BN code applies network
specific defaults `true` / `only-new`. `mainnet`: `false` / `none`.
This means that the overrides here are no longer needed, also avoiding
issues with planned renames of the parameters in the BN implementation.

disable light client data overrides

---

ansible/group_vars/nimbus.prater.yml

The branch_override is no longer necessary, because our unstable and testing branches should be building fine with Nim 1.6

Test our most recent branches with Nim 1.6

---

ansible/group_vars/nimbus.prater.yml
ansible/group_vars/nimbus.ropsten.yml
ansible/group_vars/nimbus.sepolia.yml
ansible/requirements.yml

To test our upcoming 22.11 release, we want to enable the validator client on the largest `testing` branch instance, with enabled support for an external block builder.
Before merging this, please merge
https://github.com/status-im/infra-role-validator-client/pull/1
... and bump the dependency here.

Enable the VC payload builder on linux-06's testing intance

---

ansible/group_vars/nimbus.mainnet.yml
ansible/group_vars/nimbus.prater.yml

For most nodes this is fine, except for nodes with publicly exposed API, which we should keep as synced from genesis and in archive mode.
Every other node is fine being prunned. I'm keeping AWS nodes not pruned as fallback since increasing their storage is quick and easy.

nimbus.mainnet/prater: enable pruned history

---

ansible/group_vars/nimbus.mainnet.yml
ansible/requirements.yml

To allow browser based clients to access our API servers.
Depends on:
- https://github.com/status-im/infra-role-beacon-node-linux/pull/14
- https://github.com/status-im/infra-role-beacon-node-linux/pull/15
- https://github.com/status-im/infra-role-beacon-node-macos/pull/7
- https://github.com/status-im/infra-role-beacon-node-macos/pull/8
- https://github.com/status-im/infra-role-beacon-node-windows/pull/6
- https://github.com/status-im/infra-role-beacon-node-windows/pull/7

nimbus: set `--rest-allow-origin='*'` for `public_api`

---

mainnet.tf

Nimbus logs take up to 10G on hosts.
And current disk space is 15-25%
Price increase - 1.19$ per month
https://aws.amazon.com/ebs/pricing/

nimbus.mainnet: increase stable-small root volume size

---

ansible/group_vars/nimbus.prater.yml

Removing invalid url based on @tersec request.
```
$  curl https://builder-relay-goerli.blocknative.com/eth/v1/builder/status
{"error": "Service Unavailable"}
```
List of valid URL available at https://ethstaker.cc/mev-relay-list#mev-relay-list-for-goerli-testnet

nimbus.prater: switching MEV boots url.

---

ansible/group_vars/nimbus.holesky.yml

By using the `validator_client_build_repo_branch` instead of the `node.branch`, it will create a new directory when the branch name is override.

holesky: use node branch in validator client name

---

ansible/group_vars/nimbus.mainnet.yml
ansible/host_vars/linux-01.ih-eu-mda1.nimbus.mainnet.yml
ansible/host_vars/linux-02.ih-eu-mda1.nimbus.mainnet.yml

Beacon Node stable-02 removed from host to reduce load on hosts
Manually removed from host:
* service stopped
* All files related removed
* Related consul services unregistered: 
* `build-beacon-node-mainnet-stable-02-timer`, 
* `resync-beacon-node-mainnet-stable-02-timer`
* `beacon-node-mainnet-stable-02-metrics`
* `beacon-node-mainnet-stable-02`

Remove BN stable-02 from holesky.mainnet

---

ansible/group_vars/nimbus.prater.yml

This reverts commit c48ac78797484c48e02ba613d8e8cc90b6c5527e.
The underlying issue that prompted switching to `stable` has been fixed.
- https://github.com/status-im/nimbus-eth2/issues/5753

Revert "nimbus.prater: use stable instead of unstable branch"

---

ansible/group_vars/nimbus.prater.yml

As prater is approaching end of life, it is suitable for testing edge cases with partitioned network. To avoid interfering with other networks a separate branch should be tracked instead.

nimbus.prater: use custom research branch

---

ansible/group_vars/nimbus.fluffy.yml
ansible/requirements.yml

Can also get rid of nimbus_fluffy_network_nice_name now in the process.
await https://github.com/status-im/nimbus-eth1/pull/2204 for merging

fluffy: change network to mainnet, renamed from testnet0

---

README.md
ansible/era.yml
ansible/host_vars/geth-01.ih-eu-mda1.nimbus.holesky.yml
ansible/host_vars/linux-01.ih-eu-mda1.nimbus.sepolia.yml
sepolia.tf

The PR sets up hosting for era1 files for sepolia.
Available here -> https://sepolia.era1.nimbus.team/
status: changes applied

nimbus.sepolia: host era1 files

---

ansible/group_vars/dash.nimbus.yml

Allowed access to Kibana dashboard to anyone with an account in Keycloak realm `logos-co`. Updated values in Bitwarden for client id and secret.
Referenced issue: https://github.com/status-im/infra-misc/issues/285

kibana: Moved from Github to Keycloak auth

---

ansible/group_vars/nimbus.mainnet.yml
ansible/host_vars/bootstrap-01.aws-eu-central-1a.nimbus.mainnet.yml
ansible/host_vars/bootstrap-02.aws-eu-central-1a.nimbus.mainnet.yml
ansible/host_vars/linux-01.ih-eu-mda1.nimbus.mainnet.yml
ansible/host_vars/linux-02.ih-eu-mda1.nimbus.mainnet.yml
ansible/mainnet.yml

Switch these hosts from iptables to nftables: 
[nimbus.mainnet]
- `bootstrap-01` and `bootstrap-02` required narrowed `open_ports_list` which was added in `host_vars` files
Reference: https://github.com/status-im/infra-misc/issues/301

mainnet: switch from iptables to nftables

---

ansible/group_vars/nimbus.holesky.yml
ansible/host_vars/geth-01.ih-eu-mda1.nimbus.holesky.yml
ansible/host_vars/geth-02.ih-eu-mda1.nimbus.holesky.yml

Switch `nimbus.holesky` hosts to nftables.
Reference: https://github.com/status-im/infra-misc/issues/301

holesky: switch to nftables

---

ansible/roles/nimbus-era-files/templates/verify.sh.j2

If we check only for existing files we will not notice missing files.

nimbus-era-files: check for gaps in ERA files

---

ansible/group_vars/all.yml
ansible/group_vars/dash.nimbus.yml
ansible/group_vars/logs.nimbus.yml
ansible/group_vars/nimbus-geth-holesky.yml
ansible/group_vars/nimbus-geth-mainnet.yml
ansible/group_vars/nimbus.eth1.yml
ansible/group_vars/nimbus.holesky.yml
ansible/group_vars/nimbus.mainnet.yml
ansible/group_vars/nimbus.sepolia.yml
ansible/host_vars/bootstrap-01.aws-eu-central-1a.nimbus.mainnet.yml
ansible/host_vars/bootstrap-02.aws-eu-central-1a.nimbus.mainnet.yml
ansible/host_vars/erigon-01.ih-eu-mda1.nimbus.mainnet.yml
ansible/host_vars/geth-01.ih-eu-mda1.nimbus.holesky.yml
ansible/host_vars/linux-01.ih-eu-mda1.nimbus.sepolia.yml
ansible/host_vars/nec-01.ih-eu-mda1.nimbus.mainnet.yml
ansible/mainnet.yml
ansible/requirements.yml

This PR moves over the secrets used in infra-nimbus from `bitwarden` to `vault`
I have verified these changes by running related ansible playbooks with the `--check` flag.
related issue : https://github.com/status-im/infra-hq/issues/142

Migrate to infra-nimbus from bitwarden to vault

---

ansible/bench.yml
ansible/group_vars/nimbus-bench.eth1.yml
ansible/requirements.yml

This PR uses `infra-role-nimbus-bench-eth1` to deploy short and long benchmarking service on : 
- `bench-01.he-eu-hel1.nimbus.eth1`
- `bench-02.he-eu-hel1.nimbus.eth1`

configure short and long benchmarking service

---

ansible/group_vars/nimbus.holesky.yml
ansible/group_vars/nimbus.mainnet.yml
ansible/holesky.yml
ansible/mainnet.yml
ansible/requirements.yml

This PR enables running [Nimbus Light Client](https://nimbus.guide/el-light-client.html#__tabbed_6_1) by using newly created role [infra-role-nimbus-light-client](https://github.com/status-im/infra-role-nimbus-light-client).
in stand alone mode without EL client.
Ref:
- https://github.com/status-im/infra-nimbus/issues/101

nimbus: add nimbus light-client service

---

ansible/inventory/test
hive.tf

related: https://github.com/status-im/infra-nimbus/issues/228
bootstrap newly provisioned AX41-NVMe and added to `infra-nimbus` fleet.
The host is named : `node-01.he-eu-hel1.nimbus.hive`

hive: bootstrap node-01

---

ansible/group_vars/nimbus.mainnet.yml

This PR introduces support for closing specific beacon node libp2p ports by:
- Adding a `close_libp2p_port` flag to node configuration in layout files
- Calculating which ports to close based on this flag
- Adding DROP rules before the existing ACCEPT rules to ensure they take precedence
Ref.:
- https://github.com/status-im/infra-nimbus/issues/212

mainnet: enable test of mainnet nimbus with closed libp2p port

---

ansible/group_vars/nimbus.holesky.yml
ansible/host_vars/geth-07.ih-eu-mda1.nimbus.holesky.yml
ansible/vars/layout/holesky.yml
holesky.tf

- free-up half of hosts from Holesky fleet for running `Hoodi`
- dropping `erigon` EL since we are not going to run it for now on `Hoodi` testnet
Ref.:
- https://github.com/status-im/infra-nimbus/issues/239

holesky: remove 15 out of 30 hosts from fleet

---

ansible/group_vars/nimbus.mainnet.yml
ansible/vars/layout/mainnet.yml

In previous filtering, loop was only iterating over configs where `close_libp2p_port` is true.
Close `tcp` and `udp` port for `testing` branch on:
- `nec-02.ih-eu-mda1.nimbus.mainnet`
- `erigon-01.ih-eu-mda1.nimbus.mainnet`
https://github.com/status-im/infra-nimbus/issues/212

nimbus.mainnet: close libp2p ports
